### ISSUE TITLE
Implement user interface

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#6]
See #5 for the UI/UX design.

# TODO

- [x] Implement queued vs in-transit data in settings screen.
- [x] Implement ability to change public gateway. #239
- [x] Rename app from "Gateway" to "Relaynet" (launcher menu).
- [x] Rename app from "Relaynet Gateway" to "Relaynet" (app home screen)
- [x] Gus: Do a final review of the copy. #244

**Comment by gnarea** [comment]
FYI: I was testing something unrelated to this PR, but I had left this branch installed accidentally, and I discovered that CCAs are still generated with the old gateway address. I added a log statement to confirm this.

This happened after successfully pairing with `gwmigrationtest.relaycorp.cloud`.
